Add Visual Basic support
sourcegraph/scip-dotnet pull request #26
Opened 2023-05-22 22:53 UTC by sagi1623

2023-05-23 04:43 UTC, olafurpg requested changes
@sagi1623 Thank you so much for this contribution! It's fantastic that we can support Visual Basic with so much code reuse. Nice job porting all the tests from C# to Visual Basic 👏🏻 

Only minor suggestions, I am happy to merge this PR once those are addressed.

2023-05-23 04:43 UTC, olafurpg commented on ScipDotnet/ScipIndexer.cs
> +            else
It might make sense to guard against this here
```suggestion
            else if (language == "Visual Basic")
```

2023-05-23 04:43 UTC, olafurpg commented on ScipDotnet/ScipVisualBasicSyntaxWalker.cs
> +public class ScipVisualBasicSyntaxWalker : VisualBasicSyntaxWalker
Impressive how much code reuse we can do between C# and Visual Basic!

2023-05-23 04:43 UTC, olafurpg commented on ScipDotnet/ScipSymbolFormatter.cs
> +        _languagePrefix = _doc.Language == "C#" ? "cs" : "vb";
nit: I had to check how this variable was used to understand what it does, this name might be clearer
```suggestion
        _markdownCodeFenceLanguage = _doc.Language == "C#" ? "cs" : "vb";
```

2023-05-23 04:47 UTC, olafurpg commented on ScipDotnet/ScipIndexer.cs
>  public class ScipIndexer
```suggestion
public class ScipProjectIndexer
```

2023-05-23 04:47 UTC, olafurpg commented on ScipDotnet/ScipSymbolFormatter.cs
> +public class ScipSymbolFormatter
My initial interpretation of the name `ScipSymbolFormatter` was that it formats SCIP symbols like this interface we have in Go https://sourcegraph.com/github.com/sourcegraph/scip/-/blob/bindings/go/scip/symbol_formatter.go?L10

I propose we rename this class into something else to make it clearer that this class does more than just format symbols

```suggestion
public class ScipDocumentIndexer
```

I also propose we rename `ScipIndexer` into `ScipProjectIndexer`

2023-05-24 21:16 UTC, sagi1623 commented
@olafurpg,
I have applied the suggestions you had, and I have also added in the last commit, support for indexing individual visual basic projects.
Now I would have a few other questions for you if possible:

- I have tried to follow the [guide](https://docs.sourcegraph.com/dev/how-to/add_support_for_a_language) for adding support for a new language, however my windows is misbehaving and I am unable to install sg. Because of that I would only be able to open the PRs blindly without testing, which I am not super comfortable with. May I ask you or somebody from SourceGraph to do that part?
- As VisualBasic declared member names are [case-insensitive](https://learn.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/declared-elements/declared-element-names#case-sensitivity-in-names), it can happen that we index for example a parameter as `definition scip-dotnet nuget . . VBMain/SomeClass#Method().(SomeParameter)` and later reference as `reference scip-dotnet nuget . . VBMain/SomeClass#Method().(SoMePaRaMetEr)`.
My question here is if SCIP symbol names are case sensitive or not? Will the engine know that it is the same symbol or not?
In case it is case sensitive, do you think it is at indexing that we need to handle this (for example convert the names to lower) or the engine should take care about it when loading the code intel? (I guess it depends if there are other languages with the same behavior)

2023-05-25 05:22 UTC, olafurpg commented
> May I ask you or somebody from SourceGraph to do that part?

Do you have a ready diff I can test locally? I'm happy to ensure we get Visual Basic support added.

> My question here is if SCIP symbol names are case sensitive or not? Will the engine know that it is the same symbol or not?

Good question. SCIP symbols are case sensitive so I recommend we lowercase symbols during indexing time.

2023-05-27 14:39 UTC, sagi1623 commented
>  Do you have a ready diff I can test locally? I'm happy to ensure we get Visual Basic support added.

 Not yet, I will not have time next week to work on it. If you don't mind waiting, I can try to do it the week after and send you the PRs for testing and review? 
>Good question. SCIP symbols are case sensitive so I recommend we lowercase symbols during indexing time.

Do you think we could merge this PR to limit the scope of it and I can create a new one some time later to tackle the problem of case insensitivity?

2023-05-28 06:49 UTC, olafurpg commented
> Not yet, I will not have time next week to work on it. If you don't mind waiting, I can try to do it the week after and send you the PRs for testing and review?


Sounds good. FYI, I'm doing cross-Atlantic travel for work June 4-7th so I may be slow to respond that week.

> Do you think we could merge this PR to limit the scope of it and I can create a new one some time later to tackle the problem of case insensitivity?

That's fine. I am OK with merging this PR once the CI is green. It might help to rebase on top of main now that the flaky tests have been fixed thanks to your PR #27 😄

2023-06-05 22:36 UTC, olafurpg approved these changes
LGTM 👍🏻 Thank you so much for this contribution! This is a great improvement 😄

2023-06-05 22:36 UTC, merged

2023-06-18 11:16 UTC, sagi1623 commented
Hello @olafurpg,

Coming back to our discussion regarding VbNet being case insensitive.
Actually it was a false alarm from me (sorry for that).
After revisiting the topic and testing it a bit it I realised that there is nothing to do, it works out of the box.
As we work with the semantic model and retrieve the symbols from there, it will always contain the fully defined name of the symbol as declared.
For example:
`Public Sub New(ByVal wEiRdCaSiNg As Long)` -> The definition will be VBMain/Classes#`.ctor`().(wEiRdCaSiNg)
And if it is used later with a different casing like `Property = WeIrDcAsInG` the retrieved symbol will still have the original wEiRdCaSiNg name so the reference will be -> VBMain/Classes#`.ctor`().(wEiRdCaSiNg)

2023-06-18 14:47 UTC, olafurpg commented
@sagi1623 good to confirm that. Should we update the indexer to emit case sensitive names?

2023-06-18 16:24 UTC, sagi1623 commented
> @sagi1623 good to confirm that. Should we update the indexer to emit case sensitive names?

Could you please clarify what do you mean by that?

I think that the current behaviour is correct. I mean C# is case sensitive so with whichever casing you declare a symbol you will need to reference it with the same one. For VbNet that is not the case, if you declare the symbol with one casing, you can reference it with another one. However, this difference is not syntax level. On a semantic level it will be the same symbol.
As Roslyn will give the name from the symbol, which got it from the declaration, we will always use the same casing trough the whole indexing process and I think because of this everything will work as expected once the indexing results are uploaded.

Am I missing something?

And I will soon add a new case in the snapshot project, that will document the current behaviour and should act as a safety net in case the implementation changes in the future.

2023-06-18 19:44 UTC, olafurpg commented
I thought we used all-lowercase for VB symbols but looking at the original discussion it seems like we left this change for a future PR. I agree the current behavior is correct and there's nothing we need to do 👍🏻

2023-06-19 20:22 UTC, sagi1623 commented
> I thought we used all-lowercase for VB symbols but looking at the original discussion it seems like we left this change for a future PR. I agree the current behavior is correct and there's nothing we need to do 👍🏻

Yes we said it will come in a future PR.
Once again sorry for creating the confusion. 
I have created a [PR](https://github.com/sourcegraph/scip-dotnet/pull/32) to document the behaviour and to have a test case for the future.